#include "src/game/envfx_snow.h"

const GeoLayout castle_grounds_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ROTATION_NODE_WITH_DL(LAYER_OPAQUE, 0, -90, 0, castle_grounds_dl_Building_002_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 1924, -174, 942, 0, -180, 0, castle_grounds_dl_ChairStool_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -1014, -104, 1624, 0, -24, -18, castle_grounds_dl_DiceObj_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -1019, -103, 1572, -79, -84, 90, castle_grounds_dl_DiceObj_001_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 512, -113, 1356, 0, -45, 0, castle_grounds_dl_Playing_Card_001_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 529, -113, 1336, 0, -30, 0, castle_grounds_dl_Playing_Card_002_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 541, -112, 1312, 0, -15, 0, castle_grounds_dl_Playing_Card_003_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 547, -112, 1285, castle_grounds_dl_Playing_Card_004_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 547, -112, 1252, 0, 15, 0, castle_grounds_dl_Playing_Card_005_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 1120, -113, 1385, 0, 135, 0, castle_grounds_dl_Playing_Card_006_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 1102, -113, 1405, 0, 150, 0, castle_grounds_dl_Playing_Card_007_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 677, -113, 1094, 0, -105, 0, castle_grounds_dl_Playing_Card_008_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 703, -113, 1099, 0, -90, 0, castle_grounds_dl_Playing_Card_009_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 730, -112, 1098, 0, -75, 0, castle_grounds_dl_Playing_Card_010_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 755, -112, 1090, 0, -60, 0, castle_grounds_dl_Playing_Card_011_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 784, -112, 1073, 0, -45, 0, castle_grounds_dl_Playing_Card_012_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 1090, -112, 1429, 0, 165, 0, castle_grounds_dl_Playing_Card_013_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 1084, -112, 1456, 0, -180, 0, castle_grounds_dl_Playing_Card_014_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 1084, -112, 1489, 0, -165, 0, castle_grounds_dl_Playing_Card_015_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -834, 902, 913, castle_grounds_dl_PoolTable_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 903, 970, 1169, castle_grounds_dl_RouletteTablePattern_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 985, 968, 488, castle_grounds_dl_RouletteWheel_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_SlotMachineDesign1_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_grounds_dl_SlotMachineDesign1_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_SlotMachineDesign1_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_grounds_dl_SlotMachineDesign1_001_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_SlotMachineDesign1_002_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_grounds_dl_SlotMachineDesign1_002_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_SlotMachineDesign1_003_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_grounds_dl_SlotMachineDesign1_003_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_SlotMachineDesign1_004_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_grounds_dl_SlotMachineDesign1_004_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_SlotMachineDesign1_005_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_grounds_dl_SlotMachineDesign1_005_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_SlotMachineDesign2_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_grounds_dl_SlotMachineDesign2_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_SlotMachineDesign2_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_grounds_dl_SlotMachineDesign2_001_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_SlotMachineDesign2_002_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_grounds_dl_SlotMachineDesign2_002_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_SlotMachineDesign2_003_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_grounds_dl_SlotMachineDesign2_003_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_SlotMachineDesign2_004_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_grounds_dl_SlotMachineDesign2_004_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_SlotMachineDesign2_005_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_grounds_dl_SlotMachineDesign2_005_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_SlotMachineDesign3_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_grounds_dl_SlotMachineDesign3_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_SlotMachineDesign3_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_grounds_dl_SlotMachineDesign3_001_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_SlotMachineDesign3_002_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_grounds_dl_SlotMachineDesign3_002_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_SlotMachineDesign3_003_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_grounds_dl_SlotMachineDesign3_003_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_SlotMachineDesign3_004_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_grounds_dl_SlotMachineDesign3_004_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_SlotMachineDesign3_005_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_grounds_dl_SlotMachineDesign3_005_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_SlotMachineDesign4_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_grounds_dl_SlotMachineDesign4_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_SlotMachineDesign4_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_grounds_dl_SlotMachineDesign4_001_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_SlotMachineDesign4_002_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_grounds_dl_SlotMachineDesign4_002_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_SlotMachineDesign4_003_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_grounds_dl_SlotMachineDesign4_003_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_SlotMachineDesign4_004_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_grounds_dl_SlotMachineDesign4_004_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_SlotMachineDesign4_005_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_grounds_dl_SlotMachineDesign4_005_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 100, 0, 0, castle_grounds_dl_TableOblong_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_ChairStool_013_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_ChairStool_014_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_ChairStool_015_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_ChairStool_016_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_ChairStool_017_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_ChairStool_018_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_ChairStool_019_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_ChairStool_020_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_ChairStool_021_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_ChairStool_022_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_TableRound_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_ChairStool_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_ChairStool_002_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_ChairStool_003_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_ChairStool_004_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_ChairStool_005_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_ChairStool_006_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_TableRound_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_ChairStool_007_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_ChairStool_008_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_ChairStool_009_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_ChairStool_010_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_ChairStool_011_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_ChairStool_012_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout castle_grounds_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_GREEN_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_CLOSE, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, castle_grounds_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
