extern const GeoLayout vcutm_area_1_geo[];
extern const GeoLayout vcutm_area_1[];
extern const Collision vcutm_area_1_collision[];
extern const MacroObject vcutm_area_1_macro_objs[];
extern u8 vcutm_dl__9BAE866111F9EB74BEE24DF7741B4A11_ci4[];
extern u8 vcutm_dl__9BAE866111F9EB74BEE24DF7741B4A11_pal_rgba16[];
extern u8 vcutm_dl__0001F4D8_64x64_i4_ci4[];
extern u8 vcutm_dl__0001F4D8_64x64_i4_pal_rgba16[];
extern u8 vcutm_dl_GC_0x83560_32x64_RGBA16_i8[];
extern Vtx vcutm_dl_Alley_mesh_layer_5_vtx_cull[8];
extern Vtx vcutm_dl_Alley_mesh_layer_5_vtx_0[18];
extern Gfx vcutm_dl_Alley_mesh_layer_5_tri_0[];
extern Vtx vcutm_dl_Alley_mesh_layer_5_vtx_1[93];
extern Gfx vcutm_dl_Alley_mesh_layer_5_tri_1[];
extern Vtx vcutm_dl_Dumpster_mesh_layer_1_vtx_cull[8];
extern Vtx vcutm_dl_Dumpster_mesh_layer_1_vtx_0[88];
extern Gfx vcutm_dl_Dumpster_mesh_layer_1_tri_0[];
extern Vtx vcutm_dl_Dumpster_mesh_layer_1_vtx_1[60];
extern Gfx vcutm_dl_Dumpster_mesh_layer_1_tri_1[];
extern Gfx mat_vcutm_dl_AlleyWallWarp[];
extern Gfx mat_revert_vcutm_dl_AlleyWallWarp[];
extern Gfx mat_vcutm_dl_AlleyWall[];
extern Gfx mat_revert_vcutm_dl_AlleyWall[];
extern Gfx mat_vcutm_dl_Dumpster[];
extern Gfx mat_revert_vcutm_dl_Dumpster[];
extern Gfx mat_vcutm_dl_DumpsterTop[];
extern Gfx mat_revert_vcutm_dl_DumpsterTop[];
extern Gfx vcutm_dl_Alley_mesh_layer_5[];
extern Gfx vcutm_dl_Dumpster_mesh_layer_1[];
