extern const GeoLayout sa_area_1_geo[];
extern const GeoLayout sa_area_1[];
extern const Collision sa_area_1_collision[];
extern const MacroObject sa_area_1_macro_objs[];
extern u8 sa_dl__9BAE866111F9EB74BEE24DF7741B4A11_ci4[];
extern u8 sa_dl__9BAE866111F9EB74BEE24DF7741B4A11_pal_rgba16[];
extern u8 sa_dl__0001F4D8_64x64_i4_ci4[];
extern u8 sa_dl__0001F4D8_64x64_i4_pal_rgba16[];
extern u8 sa_dl_GC_0x83560_32x64_RGBA16_i8[];
extern Vtx sa_dl_Alley_mesh_layer_5_vtx_cull[8];
extern Vtx sa_dl_Alley_mesh_layer_5_vtx_0[18];
extern Gfx sa_dl_Alley_mesh_layer_5_tri_0[];
extern Vtx sa_dl_Alley_mesh_layer_5_vtx_1[93];
extern Gfx sa_dl_Alley_mesh_layer_5_tri_1[];
extern Vtx sa_dl_Dumpster_mesh_layer_1_vtx_cull[8];
extern Vtx sa_dl_Dumpster_mesh_layer_1_vtx_0[88];
extern Gfx sa_dl_Dumpster_mesh_layer_1_tri_0[];
extern Vtx sa_dl_Dumpster_mesh_layer_1_vtx_1[60];
extern Gfx sa_dl_Dumpster_mesh_layer_1_tri_1[];
extern Gfx mat_sa_dl_AlleyWallWarp[];
extern Gfx mat_revert_sa_dl_AlleyWallWarp[];
extern Gfx mat_sa_dl_AlleyWall[];
extern Gfx mat_revert_sa_dl_AlleyWall[];
extern Gfx mat_sa_dl_Dumpster[];
extern Gfx mat_revert_sa_dl_Dumpster[];
extern Gfx mat_sa_dl_DumpsterTop[];
extern Gfx mat_revert_sa_dl_DumpsterTop[];
extern Gfx sa_dl_Alley_mesh_layer_5[];
extern Gfx sa_dl_Dumpster_mesh_layer_1[];
