extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Lights1 bob_dl_f3dlite_material_001_lights;
extern Lights1 bob_dl_f3dlite_material_002_lights;
extern Lights1 bob_dl_grond2_lights;
extern Lights1 bob_dl_grond_001_lights;
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_001_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cube_001_mesh_layer_1_vtx_0[24];
extern Gfx bob_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Floaty_Blue_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Floaty_Blue_Cube_mesh_layer_1_vtx_0[24];
extern Gfx bob_dl_Floaty_Blue_Cube_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_0[108];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_0[];
extern Gfx mat_bob_dl_f3dlite_material_001[];
extern Gfx mat_bob_dl_f3dlite_material_002[];
extern Gfx mat_bob_dl_grond2[];
extern Gfx mat_bob_dl_grond_001[];
extern Gfx bob_dl_Cube_mesh_layer_1[];
extern Gfx bob_dl_Cube_001_mesh_layer_1[];
extern Gfx bob_dl_Floaty_Blue_Cube_mesh_layer_1[];
extern Gfx bob_dl_Plane_mesh_layer_1[];
extern const Trajectory castle_courtyard_area_2_spline_ballpath[];

