extern const GeoLayout pss_area_1_geo[];
extern const GeoLayout pss_area_1[];
extern const Collision pss_area_1_collision[];
extern const MacroObject pss_area_1_macro_objs[];
extern Lights1 pss_dl_f3dlite_material_001_lights;
extern Lights1 pss_dl_f3dlite_material_002_lights;
extern Lights1 pss_dl_grond2_lights;
extern Lights1 pss_dl_grond_001_lights;
extern Vtx pss_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx pss_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx pss_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx pss_dl_Cube_001_mesh_layer_1_vtx_cull[8];
extern Vtx pss_dl_Cube_001_mesh_layer_1_vtx_0[24];
extern Gfx pss_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx pss_dl_Floaty_Blue_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx pss_dl_Floaty_Blue_Cube_mesh_layer_1_vtx_0[24];
extern Gfx pss_dl_Floaty_Blue_Cube_mesh_layer_1_tri_0[];
extern Vtx pss_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx pss_dl_Plane_mesh_layer_1_vtx_0[108];
extern Gfx pss_dl_Plane_mesh_layer_1_tri_0[];
extern Gfx mat_pss_dl_f3dlite_material_001[];
extern Gfx mat_pss_dl_f3dlite_material_002[];
extern Gfx mat_pss_dl_grond2[];
extern Gfx mat_pss_dl_grond_001[];
extern Gfx pss_dl_Cube_mesh_layer_1[];
extern Gfx pss_dl_Cube_001_mesh_layer_1[];
extern Gfx pss_dl_Floaty_Blue_Cube_mesh_layer_1[];
extern Gfx pss_dl_Plane_mesh_layer_1[];
